<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>ProfWorld</title>';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" defer integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>';
echo '<link rel="stylesheet" href="/styles.css">';
echo '</head>';
echo '<body class="container-fluid">';
echo '<div class="row homepage-container">';
echo '<aside class="Homepage-sidebar col-2">';
echo '<nav class="sidebar-nav">';
echo '<a href="/" class="navbar-brand"><img src="/logo-removebg-preview.png" alt=""></a>';
echo '<ul class="list-unstyled">';
echo '<li><a href="/app/index.html">Welcome</a></li>';
echo '<li><a href="/app/createtest.html">Create Test</a></li>';
echo '<li><a href="/app/previoustests.html">Previous Tests</a></li>';
echo '<li><a href="/app/performance.html">Performance</a></li>';
echo '<li><a href="#">Search</a></li>';
echo '<li><a href="/app/notes.html">Notes</a></li>';
echo '<li><a href="/app/flashcards.html">Flash Cards</a></li>';
echo '<li><a href="/app/help.html">Help</a></li>';
echo '</ul>';
echo '</nav>';
echo '</aside>';
echo '<main class="content col-10">';
echo '<header class="header container-fluid ">';
echo '';
echo '<nav class="navbar navbar-expand-lg navbar-light bg-light col-12 ">';
echo '<div class="container-xxl">';
echo '<h1>Welcome, John</h1>';
echo '<!-- OPTIONAL LOGO: <a href="/" class="navbar-brand">Logo</a>-->';
echo '';
echo '<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarSupportedContent">';
echo '<ul class="navbar-nav ms-auto">';
echo '<li class="nav-item">';
echo '<a href="/" class="nav-link">Test Date</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a href="/about" class="nav-link">My Account</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a href="/contact" class="nav-link">Sign Out</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</header>';
echo '<section class="statistics">';
echo '<div class="main-row-1 main-row row ">';
echo '<div class="category col-6" style="flex-basis: 45%; margin: 10px; text-align: left;">';
echo '<h2>QBank Usage</h2>';
echo '<p><span>Used Questions: </span><span id="usedQuestions">0</span></p>';
echo '<p><span>Unused Questions: </span><span id="unusedQuestions">0</span></p>';
echo '<p><span>Total Questions: </span><span id="totalQuestions">0</span></p>';
echo '</div>';
echo '';
echo '<div class="category col-6" style="flex-basis: 45%; margin: 10px; text-align: right;">';
echo '<h2>Answers Changed</h2>';
echo '<p><span>Correct to Incorrect: </span> <span id="correctToIncorrect">0</span></p>';
echo '<p><span>Incorrect to Correct: </span> <span id="incorrectToCorrect">0</span></p>';
echo '<p><span>Incorrect to Incorrect: </span> <span id="incorrectToIncorrect">0</span></p>';
echo '</div>';
echo '</div>';
echo '<div class="main-row-2 main-row row">';
echo '';
echo '<div class="category col-6" style="flex-basis: 45%; margin: 10px; text-align: left;">';
echo '<h2>Your Score</h2>';
echo '<p><span>Total Correct: </span><span id="totalCorrect">0</span></p>';
echo '<p><span>Total Incorrect: </span><span id="totalIncorrect">0</span></p>';
echo '<p><span>Total Completed: </span><span id="totalOmitted">0</span></p>';
echo '</div>';
echo '';
echo '<div class="category col-6" style="flex-basis: 45%; margin: 10px; text-align: right;">';
echo '<h2>Test Count</h2>';
echo '<p><span>Tests Created: </span><span id="testsCreated">0</span></p>';
echo '<p><span>Tests Completed: </span><span id="testsCompleted">0</span></p>';
echo '<p><span>Suspended Tests: </span><span id="suspendedTests">0</span></p>';
echo '</div>';
echo '</div>';
echo '</section>';
echo '<!-- Content of the selected tab will go here -->';
echo '</main>';
echo '</div>';
echo '</body>';
echo '</html>';
?>